[package]
name = "ansi-to-tui"
version = "0.5.0"
authors = ["Uttarayan Mondal <uttarayan21@gmail.com>"]
edition = "2021"
description = "A library to convert ansi color coded text into tui::text::Text type from tui-rs library"
keywords = ["ansi", "ascii", "tui", "parser"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/uttarayan21/ansi-to-tui"
exclude = [
    ".github/*",
    "ascii",
    "tests",
]

[dependencies]
simdutf8 = { version = "0.1.1", optional = true }
tui = { version = "0.17.0", default-features = false }

[dev-dependencies]
anyhow = "1.0.40"

[features]
simd = ["simdutf8"]
